### ISSUE TITLE
`prefers-reduced-motion` not set to `reduce` results in screenshots being taken mid-animation.

### ISSUE THREAD

**Issue by nicolasgasco** [argos-ci/argos-ember#1]
Hello!

I'm trying to take a screenshot of a page that has a fade-in animation on render.

 I played around with CSS resets, but I couldn't reach a satisfactory result. The screenshot is being taken mid-animation:
<img src="https://github.com/argos-ci/argos-ember/assets/73175085/6e34f273-8e92-4306-8ac6-5dc816dba3f5" width="450" />

I was finally able to take a good screenshot by emulating `prefers-reduced-motion="reduce"` on the Puppeteer page object: 
<img src="https://github.com/argos-ci/argos-ember/assets/73175085/58edab41-4851-4a53-b3b1-830f9341ffa0" width="450" />

```diff
// node_modules/@argos-ci/ember/run-chrome.mjs

  app.post("/screenshot", express.json(), async (req, res) => {
    try {
      // Take a screenshot of the page
      const element = await page.$("#ember-testing");
      if (!element) {
        throw new Error("No #ember-testing element found");
      }
      const { name, ...options } = req.body;

+      page.emulateMediaFeatures([
+        { name: "prefers-reduced-motion", value: "reduce" },
+      ]);

      await argosScreenshot(page, name, {
        element,
        ...options,
      });
      res.sendStatus(200);
    } catch (error) {
      res.send(error.stack);
      console.error(error);
      res.sendStatus(500);
    }
  });
```

In the snippet, `prefers-reduce-motion` is set to `reduce` by default, which seems consistent with the fact that animations are not something that you might want to do visual regression testing on.

I think this could also be an option, but it gets filtered out somewhere down the line. I believe by the TypeScript configuration since  it's not part of `PuppeteerArgosScreenshotOptions`.

**Comment by gregberge** [comment]
@nicolasgasco I will just add it, it's not a big deal for now. If someone complains about it I would create an option to disable this behaviour.

**Comment by nicolasgasco** [comment]
Thanks a lot for fixing this!
